// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SHOW_ACCOUNT = 'SHOW_ACCOUNT'
export const CLOSE_ACCOUNT = 'CLOSE_ACCOUNT'

// Alert
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// Admin
export const GET_ALL_USER = 'GET_ALL_USER'
export const REQ_FAIL = 'REQ_FAIL'
export const SET_ADMIN_EDIT = 'SET_ADMIN_EDIT'

//Home
export const HOME_SET_SHOW_POPUP = 'HOME_SET_SHOW_POPUP'
export const HOME_SET_SHOW_USER = 'HOME_SET_SHOW_USER'
export const HOME_SET_CLOSE_POPUP = 'HOME_SET_CLOSE_POPUP'
export const HOME_GET_USER_MATCHES = 'HOME_GET_USER_MATCHES'

export const HOME_HANDLE_CHANGE = 'HOME_HANDLE_CHANGE'
export const HOME_HANDLE_SUBMIT = 'HOME_HANDLE_SUBMIT'
export const HOME_SET_ALL_MATCHES ='HOME_SET_ALL_MATCHES'

//POST
export const POST_SET_SHOW_POPUP = 'POST_SET_SHOW_POPUP'
export const POST_SET_CLOSE_POPUP = 'POST_SET_CLOSE_POPUP'
export const POST_SET_SHOW_POST = 'POST_SET_SHOW_POST'
export const POST_SET_NEW_POST_DISPLAY = 'POST_SET_NEW_POST_DISPLAY'
export const POST_SET_CLOSE_NEW_POST_DISPLAY = 'POST_SET_CLOSE_NEW_POST_DISPLAY'
export const POST_SET_USER = 'POST_SET_USER'
export const POST_LOAD_POST = 'POST_LOAD_POST'
export const POST_LOAD_POST_FAIL = 'POST_LOAD_POST_FAIL'
export const POST_RELOAD_SHOW_POST = 'POST_RELOAD_SHOW_POST'
export const POST_RELOAD_ALL_POST = 'POST_RELOAD_ALL_POST'
export const POST_UPDATE_SHOW_COMMENTS_STATUS = 'POST_UPDATE_SHOW_COMMENTS_STATUS'
export const POST_LOAD_FRIENDS_LIST = 'POST_LOAD_FRIENDS_LIST'
export const POST_POSTS = 'POST_POSTS'

// Chat
export const GET_CHATS = 'GET_CHATS'
export const REGISTER_CHAT = 'REGISTER_CHAT'

// ALL
export const LOADING = 'LOADING'
